on: [push, pull_request]
name: main
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build and Test
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v0.6
        with:
          architecture: x64
          version: 7.6
      - run: raco pkg install --batch --auto --name rackcheck
      - run: raco test .
      - run: raco test examples/*
