on: [push, pull_request]
name: main
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        racket-version: [ '7.6', '8.0', 'current' ]
    name: Build and Test on Racket ${{ matrix.racket-version }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.1
        with:
          architecture: x64
          version: ${{ matrix.racket-version }}
      - run: raco pkg install --batch --auto ./rackcheck-lib
      - run: raco pkg install --batch --auto ./rackcheck
      - run: raco test rackcheck-lib
      - run: raco test examples/*
